### ISSUE TITLE
Windows: Error when sending a message

### ISSUE THREAD

**Issue by devinprater** [chigkim/VOLlama#3]
This may be a compatibility issue between Vollama and newer Ollama versions. I just redownloaded Vollama, beta 4 I think? The newest one from June. There isn't an About menu item that I could find so I can't definitively tell you the version number. So, I have Llama 3.1 8B downloaded, so I sent it a message, and got the below error:

Server error '500 Internal Server Error' for url 'http://localhost:11434/api/chat'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
Traceback (most recent call last):
  File "Model.py", line 188, in ask
  File "llama_index\core\llms\callbacks.py", line 154, in wrapped_gen
  File "llama_index\llms\ollama\base.py", line 178, in stream_chat
  File "httpx\_models.py", line 761, in raise_for_status
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://localhost:11434/api/chat'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

**Comment by chigkim** [comment]
Which Ollama version are you using?
I just tested with 0.3.13, and it worked for me.
