### ISSUE TITLE
Document build process

### ISSUE THREAD

**Issue by ogomez92** [chigkim/VOLlama#4]
Hello,
I'm struggling a bit to build this on mac. I created a Conda environment with python 3.11 since it seems to be required by this tool, based on it looking for a file in python 3.11 when building. basically I want to build it for ARM64.

However it's looking inside a .venv folder. Do I need to create a virtual environment instead? It seems strange that there is no requirements file also.

Steps:
1.  Created conda environment.
2. Installed requirements.txt
3. ./build.sh

result:
 '/Volumes/ssd/code/python/VOLlama']
2795 INFO: Appending 'datas' from .spec
Unable to find '/Volumes/ssd/code/python/VOLlama/.venv/Lib/python3.11/site-packages/llama_index/core/_static/nltk_cache' when adding binary and data files.
(vollama) uri@mini VOLlama % 

Thanks.

**Comment by chigkim** [comment]
Yes, definitely create virtual environment with python -m venv .venv.
Also there should be requirements.txt if you cloned it.
https://github.com/chigkim/VOLlama/blob/main/requirements.txt
However, requirements.txt does not specify versions, so it won't be compatible if you build with latest dependencies unfortunately.
I have to either go back and track down which versions are compatible or make VOLllama to work with latest dependencies.

**Comment by ogomez92** [comment]
It seems to build fine without specifying versions. I had it built and
notarized under my own account and it seems to load fine.

**Comment by chigkim** [comment]
It may build fine, but some of the features won't work anymore. For example, sending image to a vision model via Ollama.

**Comment by chigkim** [comment]
I provided patch to work with latest dependencies.

```bash
pip install -r requirements.txt
git apply lib-win.patch
```

If you're on mac, use lib-mac.patch instead.
